### ISSUE TITLE
JsonAstParser depends on the current system culture

### ISSUE THREAD

**Issue by sk-pub** [cosullivan/JsonLite#1]
For example, JsonAstParser.MakeDecimal() uses the method Decimal.TryParse() without format provider. Because of that, it fails to parse valid numbers on systems with comma as number delimiter in regional settings.

According to JSON standard, numbers must always use a dot as a decimal separator: https://tools.ietf.org/html/rfc7159.html#section-6
Thus, JsonAstParser() must use CultureInfo.InvariantCulture as a format provider.

**Comment by cosullivan** [comment]
Thanks for picking that up. I've just updated the code and Nuget package.

**Comment by sk-pub** [comment]
@cosullivan , please also update Hypermedia.JsonApi and Hypermedia.JsonApi.Client packages to use the latest JsonLite library. I, actually, faced this issue while using the Hypermedia Json API client.

**Comment by cosullivan** [comment]
@unicrus I have published new versions of the packages now.

Thanks,
Cain.
